faq:
    resource: "@FaqBundle/Controller/"
    type:     annotation
    prefix:   /

why_choose:
    resource: "@WhyChooseBundle/Controller/"
    type:     annotation
    prefix:   /

diplomas:
    resource: "@DiplomasBundle/Controller/"
    type:     annotation
    prefix:   /

cooperation:
    resource: "@CooperationBundle/Controller/"
    type:     annotation
    prefix:   /

account:
    resource: "@AccountBundle/Controller/"
    type:     annotation
    prefix:   /

contacts:
    resource: "@ContactsBundle/Controller/"
    type:     annotation
    prefix:   /

about:
    resource: "@AboutBundle/Controller/"
    type:     annotation
    prefix:   /

#category:
#    resource: "@CategoryBundle/Controller/"
#    type:     annotation
#    prefix:   /
#
#api:
#    resource: "@ApiBundle/Controller/"
#    type:     annotation
#    prefix:   /
#
#page:
#    resource: "@PageBundle/Controller/"
#    type:     annotation
#    prefix:   /
#    defaults:
#        _locale: ru
#    requirements:
#        _locale: ru|ky|en
#
#aio_gallery:
#    resource: "@GalleryBundle/Controller/"
#    type:     annotation
#    prefix:   /
#    defaults:
#        _locale: ru
#    requirements:
#        _locale: ru|ky|en

main:
    resource: "@MainBundle/Controller/"
    type:     annotation
    prefix:   /
    defaults:
        _locale: ru
    requirements:
        _locale: ru|ky|en

aio_core:
    resource: "@AiOCoreBundle/Resources/config/routing.yml"
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /aio-api/doc

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

application_media:
    resource: '@ApplicationSonataMediaBundle/Resources/config/routing.yml'
    prefix: /application/media

sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /resetting

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /profile

sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /register

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /profile

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /aio-admin

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /aio-admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /aio-admin

