services:
#    main.example:
#        class: MainBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    main.translate:
        class: MainBundle\Services\MainService
        arguments: ["@doctrine.orm.entity_manager"]

    main.admin.translate:
        class: MainBundle\Admin\TranslateAdmin
        arguments: [~, MainBundle\Entity\Translate, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Переводы, label: Переводы слов }

    main.admin.text_translate:
        class: MainBundle\Admin\TextTranslateAdmin
        arguments: [~, MainBundle\Entity\TextTranslate, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Переводы, label: Переводы текстов }

